package com.entrobus.credit.log.dao;

import com.entrobus.credit.pojo.log.ClientLog;
import com.entrobus.credit.pojo.log.ClientLogExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ClientLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_log
     *
     * @mbggenerated
     */
    int countByExample(ClientLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_log
     *
     * @mbggenerated
     */
    int deleteByExample(ClientLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_log
     *
     * @mbggenerated
     */
    int insert(ClientLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_log
     *
     * @mbggenerated
     */
    int insertSelective(ClientLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_log
     *
     * @mbggenerated
     */
    List<ClientLog> selectByExampleWithBLOBs(ClientLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_log
     *
     * @mbggenerated
     */
    List<ClientLog> selectByExample(ClientLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_log
     *
     * @mbggenerated
     */
    ClientLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ClientLog record, @Param("example") ClientLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_log
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") ClientLog record, @Param("example") ClientLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ClientLog record, @Param("example") ClientLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ClientLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ClientLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ClientLog record);

    int insertBatchSelective(List<ClientLog> records);

    int updateBatchByPrimaryKeySelective(List<ClientLog> records);
}