package com.entrobus.credit.log.dao;

import com.entrobus.credit.pojo.log.OperationLogTableColumn;
import com.entrobus.credit.pojo.log.OperationLogTableColumnExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OperationLogTableColumnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_log_table_column
     *
     * @mbggenerated
     */
    int countByExample(OperationLogTableColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_log_table_column
     *
     * @mbggenerated
     */
    int deleteByExample(OperationLogTableColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_log_table_column
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_log_table_column
     *
     * @mbggenerated
     */
    int insert(OperationLogTableColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_log_table_column
     *
     * @mbggenerated
     */
    int insertSelective(OperationLogTableColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_log_table_column
     *
     * @mbggenerated
     */
    List<OperationLogTableColumn> selectByExample(OperationLogTableColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_log_table_column
     *
     * @mbggenerated
     */
    OperationLogTableColumn selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_log_table_column
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OperationLogTableColumn record, @Param("example") OperationLogTableColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_log_table_column
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OperationLogTableColumn record, @Param("example") OperationLogTableColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_log_table_column
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OperationLogTableColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_log_table_column
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OperationLogTableColumn record);
}