server:
  port: 8888

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@localhost:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitlab.newseax.common/credit/creditlife
          search-paths: config-repo
#server:
#  port: 8088
#spring:
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        health:
#          enabled:  false
#        native:
#          searchLocations: D:/ideaprojects/cloud-config-repo

  rabbitmq:
    host: localhost

#security:
#  user:
#    name: user
#    password: ${CONFIG_SERVER_PASSWORD:password}
