server:
  port: 8888

eureka:
  instance:
    hostname: 10.135.106.153:8761
    prefer-ip-address: true
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@${eureka.instance.hostname}/eureka/


# 启用配置加密
encrypt:
  key-store:
    alias: creditlife
    location: creditlife-config.jks
    secret: Lee7edee9w
    password: eiy6eeBief

#server:
#  port: 8088
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitlab.newseax.com/credit/creditlife.git
          search-paths: config-repo
          username: root
          password: KcjJb17151

# 测试环境rabbitmq服务器地址
  rabbitmq:
    host: 10.104.78.27
    port: 5672
    username: newseax-test
    password: 123
    virtual-host: newseax-test

security:
  user:
    name: user
    password: ${CONFIG_SERVER_PASSWORD:password}
  basic:
    enabled: false

management:
  security:
    enabled: false