eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@localhost:8761/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

spring:
  rabbitmq:
    host: localhost
  sleuth:
    sampler:
      percentage: 1
    integration:
      enabled: false
    scheduled:
      skip-pattern: "^org.*HystrixStreamTask$"
  redis:
    cluster:
      nodes:
        - 10.1.1.241:7000
        - 10.1.1.241:7001
        - 10.1.1.241:7002
        - 10.1.1.241:7003
        - 10.1.1.241:7004
        - 10.1.1.241:7005

authserver:
    hostname: localhost
    port: 5000
    contextPath: /uaa

#security:
#  oauth2:
#    resource:
#      user-info-uri: http://${authserver.hostname}:${authserver.port}${authserver.contextPath}/current



