server:
  port: 8092
  
msg: file-service

eureka:
  instance:
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}

spring:
#测试环境redis
  redis:
    cluster:
      nodes:
        - 10.104.70.51:7000
        - 10.104.70.51:7001
        - 10.104.70.51:7002
        - 10.104.70.51:7003
        - 10.104.70.51:7004
        - 10.104.70.51:7005

security:
  user:
    name: user
    password: password
#  oauth2:
#    client:
#      clientId: order-service
#      clientSecret: ${security.user.password}
#      accessTokenUri: http://${authserver.hostname}:${authserver.port}${authserver.contextPath}/oauth/token
#      grant-type: client_credentials
#      scope: server