server:
  port: 8093
  
msg: payment-service

eureka:
  instance:
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}

spring:
#配置generate-sub-order topic 订阅者
  cloud:
    stream:
      bindings:
        generate_sub_order_subscribe:
          destination: generate-sub-order
          consumer:
            durableSubscription: true

security:
  user:
    name: user
    password: password
#  oauth2:
#    client:
#      clientId: order-service
#      clientSecret: ${security.user.password}
#      accessTokenUri: http://${authserver.hostname}:${authserver.port}${authserver.contextPath}/oauth/token
#      grant-type: client_credentials
#      scope: server