package com.entrobus.credit.pojo.payment;

import java.io.Serializable;
import java.util.Date;

public class RepaymentInstance implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_instance.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_instance.order_id
     *
     * @mbggenerated
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_instance.repayment_plan_id
     *
     * @mbggenerated
     */
    private String repaymentPlanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_instance.repayment_id
     *
     * @mbggenerated
     */
    private String repaymentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_instance.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_instance.account
     *
     * @mbggenerated
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_instance.account_id
     *
     * @mbggenerated
     */
    private String accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_instance.plan_time
     *
     * @mbggenerated
     */
    private Date planTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_instance.plan_money
     *
     * @mbggenerated
     */
    private Long planMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_instance.create_operator
     *
     * @mbggenerated
     */
    private String createOperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_instance.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_instance.delay_state
     *
     * @mbggenerated
     */
    private Integer delayState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_instance.delay_times
     *
     * @mbggenerated
     */
    private Date delayTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_instance.repayment_time
     *
     * @mbggenerated
     */
    private Date repaymentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_instance.repayment_money
     *
     * @mbggenerated
     */
    private Long repaymentMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayment_instance.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table repayment_instance
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_instance.id
     *
     * @return the value of repayment_instance.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_instance.id
     *
     * @param id the value for repayment_instance.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_instance.order_id
     *
     * @return the value of repayment_instance.order_id
     *
     * @mbggenerated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_instance.order_id
     *
     * @param orderId the value for repayment_instance.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_instance.repayment_plan_id
     *
     * @return the value of repayment_instance.repayment_plan_id
     *
     * @mbggenerated
     */
    public String getRepaymentPlanId() {
        return repaymentPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_instance.repayment_plan_id
     *
     * @param repaymentPlanId the value for repayment_instance.repayment_plan_id
     *
     * @mbggenerated
     */
    public void setRepaymentPlanId(String repaymentPlanId) {
        this.repaymentPlanId = repaymentPlanId == null ? null : repaymentPlanId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_instance.repayment_id
     *
     * @return the value of repayment_instance.repayment_id
     *
     * @mbggenerated
     */
    public String getRepaymentId() {
        return repaymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_instance.repayment_id
     *
     * @param repaymentId the value for repayment_instance.repayment_id
     *
     * @mbggenerated
     */
    public void setRepaymentId(String repaymentId) {
        this.repaymentId = repaymentId == null ? null : repaymentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_instance.user_id
     *
     * @return the value of repayment_instance.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_instance.user_id
     *
     * @param userId the value for repayment_instance.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_instance.account
     *
     * @return the value of repayment_instance.account
     *
     * @mbggenerated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_instance.account
     *
     * @param account the value for repayment_instance.account
     *
     * @mbggenerated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_instance.account_id
     *
     * @return the value of repayment_instance.account_id
     *
     * @mbggenerated
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_instance.account_id
     *
     * @param accountId the value for repayment_instance.account_id
     *
     * @mbggenerated
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_instance.plan_time
     *
     * @return the value of repayment_instance.plan_time
     *
     * @mbggenerated
     */
    public Date getPlanTime() {
        return planTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_instance.plan_time
     *
     * @param planTime the value for repayment_instance.plan_time
     *
     * @mbggenerated
     */
    public void setPlanTime(Date planTime) {
        this.planTime = planTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_instance.plan_money
     *
     * @return the value of repayment_instance.plan_money
     *
     * @mbggenerated
     */
    public Long getPlanMoney() {
        return planMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_instance.plan_money
     *
     * @param planMoney the value for repayment_instance.plan_money
     *
     * @mbggenerated
     */
    public void setPlanMoney(Long planMoney) {
        this.planMoney = planMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_instance.create_operator
     *
     * @return the value of repayment_instance.create_operator
     *
     * @mbggenerated
     */
    public String getCreateOperator() {
        return createOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_instance.create_operator
     *
     * @param createOperator the value for repayment_instance.create_operator
     *
     * @mbggenerated
     */
    public void setCreateOperator(String createOperator) {
        this.createOperator = createOperator == null ? null : createOperator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_instance.remark
     *
     * @return the value of repayment_instance.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_instance.remark
     *
     * @param remark the value for repayment_instance.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_instance.delay_state
     *
     * @return the value of repayment_instance.delay_state
     *
     * @mbggenerated
     */
    public Integer getDelayState() {
        return delayState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_instance.delay_state
     *
     * @param delayState the value for repayment_instance.delay_state
     *
     * @mbggenerated
     */
    public void setDelayState(Integer delayState) {
        this.delayState = delayState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_instance.delay_times
     *
     * @return the value of repayment_instance.delay_times
     *
     * @mbggenerated
     */
    public Date getDelayTimes() {
        return delayTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_instance.delay_times
     *
     * @param delayTimes the value for repayment_instance.delay_times
     *
     * @mbggenerated
     */
    public void setDelayTimes(Date delayTimes) {
        this.delayTimes = delayTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_instance.repayment_time
     *
     * @return the value of repayment_instance.repayment_time
     *
     * @mbggenerated
     */
    public Date getRepaymentTime() {
        return repaymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_instance.repayment_time
     *
     * @param repaymentTime the value for repayment_instance.repayment_time
     *
     * @mbggenerated
     */
    public void setRepaymentTime(Date repaymentTime) {
        this.repaymentTime = repaymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_instance.repayment_money
     *
     * @return the value of repayment_instance.repayment_money
     *
     * @mbggenerated
     */
    public Long getRepaymentMoney() {
        return repaymentMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_instance.repayment_money
     *
     * @param repaymentMoney the value for repayment_instance.repayment_money
     *
     * @mbggenerated
     */
    public void setRepaymentMoney(Long repaymentMoney) {
        this.repaymentMoney = repaymentMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayment_instance.create_time
     *
     * @return the value of repayment_instance.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayment_instance.create_time
     *
     * @param createTime the value for repayment_instance.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}