package com.entrobus.credit.pojo.wechat;

import java.io.Serializable;
import java.util.Date;

public class WechatUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.open_id
     *
     * @mbggenerated
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.subscribe_time
     *
     * @mbggenerated
     */
    private Date subscribeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.unsubscribe_time
     *
     * @mbggenerated
     */
    private Date unsubscribeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.public_account_id
     *
     * @mbggenerated
     */
    private String publicAccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.subscribe_status
     *
     * @mbggenerated
     */
    private Integer subscribeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.nickname
     *
     * @mbggenerated
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.sex
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.language
     *
     * @mbggenerated
     */
    private String language;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.province
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.country
     *
     * @mbggenerated
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.headImgUrl
     *
     * @mbggenerated
     */
    private String headimgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.union_id
     *
     * @mbggenerated
     */
    private String unionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wechat_user
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.id
     *
     * @return the value of wechat_user.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.id
     *
     * @param id the value for wechat_user.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.open_id
     *
     * @return the value of wechat_user.open_id
     *
     * @mbggenerated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.open_id
     *
     * @param openId the value for wechat_user.open_id
     *
     * @mbggenerated
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.subscribe_time
     *
     * @return the value of wechat_user.subscribe_time
     *
     * @mbggenerated
     */
    public Date getSubscribeTime() {
        return subscribeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.subscribe_time
     *
     * @param subscribeTime the value for wechat_user.subscribe_time
     *
     * @mbggenerated
     */
    public void setSubscribeTime(Date subscribeTime) {
        this.subscribeTime = subscribeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.unsubscribe_time
     *
     * @return the value of wechat_user.unsubscribe_time
     *
     * @mbggenerated
     */
    public Date getUnsubscribeTime() {
        return unsubscribeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.unsubscribe_time
     *
     * @param unsubscribeTime the value for wechat_user.unsubscribe_time
     *
     * @mbggenerated
     */
    public void setUnsubscribeTime(Date unsubscribeTime) {
        this.unsubscribeTime = unsubscribeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.public_account_id
     *
     * @return the value of wechat_user.public_account_id
     *
     * @mbggenerated
     */
    public String getPublicAccountId() {
        return publicAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.public_account_id
     *
     * @param publicAccountId the value for wechat_user.public_account_id
     *
     * @mbggenerated
     */
    public void setPublicAccountId(String publicAccountId) {
        this.publicAccountId = publicAccountId == null ? null : publicAccountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.subscribe_status
     *
     * @return the value of wechat_user.subscribe_status
     *
     * @mbggenerated
     */
    public Integer getSubscribeStatus() {
        return subscribeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.subscribe_status
     *
     * @param subscribeStatus the value for wechat_user.subscribe_status
     *
     * @mbggenerated
     */
    public void setSubscribeStatus(Integer subscribeStatus) {
        this.subscribeStatus = subscribeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.nickname
     *
     * @return the value of wechat_user.nickname
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.nickname
     *
     * @param nickname the value for wechat_user.nickname
     *
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.sex
     *
     * @return the value of wechat_user.sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.sex
     *
     * @param sex the value for wechat_user.sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.language
     *
     * @return the value of wechat_user.language
     *
     * @mbggenerated
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.language
     *
     * @param language the value for wechat_user.language
     *
     * @mbggenerated
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.city
     *
     * @return the value of wechat_user.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.city
     *
     * @param city the value for wechat_user.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.province
     *
     * @return the value of wechat_user.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.province
     *
     * @param province the value for wechat_user.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.country
     *
     * @return the value of wechat_user.country
     *
     * @mbggenerated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.country
     *
     * @param country the value for wechat_user.country
     *
     * @mbggenerated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.headImgUrl
     *
     * @return the value of wechat_user.headImgUrl
     *
     * @mbggenerated
     */
    public String getHeadimgurl() {
        return headimgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.headImgUrl
     *
     * @param headimgurl the value for wechat_user.headImgUrl
     *
     * @mbggenerated
     */
    public void setHeadimgurl(String headimgurl) {
        this.headimgurl = headimgurl == null ? null : headimgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.create_time
     *
     * @return the value of wechat_user.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.create_time
     *
     * @param createTime the value for wechat_user.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.update_time
     *
     * @return the value of wechat_user.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.update_time
     *
     * @param updateTime the value for wechat_user.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.union_id
     *
     * @return the value of wechat_user.union_id
     *
     * @mbggenerated
     */
    public String getUnionId() {
        return unionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.union_id
     *
     * @param unionId the value for wechat_user.union_id
     *
     * @mbggenerated
     */
    public void setUnionId(String unionId) {
        this.unionId = unionId == null ? null : unionId.trim();
    }
}