package com.entrobus.credit.pojo.wechat;

import java.io.Serializable;
import java.util.Date;

public class WechatPublicAccount implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_public_account.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_public_account.account_id
     *
     * @mbggenerated
     */
    private String accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_public_account.account_name
     *
     * @mbggenerated
     */
    private String accountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_public_account.app_id
     *
     * @mbggenerated
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_public_account.app_secret
     *
     * @mbggenerated
     */
    private String appSecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_public_account.token
     *
     * @mbggenerated
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_public_account.ticket
     *
     * @mbggenerated
     */
    private String ticket;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_public_account.valid_state
     *
     * @mbggenerated
     */
    private Integer validState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_public_account.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_public_account.aes_key
     *
     * @mbggenerated
     */
    private String aesKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_public_account.partener_id
     *
     * @mbggenerated
     */
    private String partenerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_public_account.partener_key
     *
     * @mbggenerated
     */
    private String partenerKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_public_account.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_public_account.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_public_account.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_public_account.delete_time
     *
     * @mbggenerated
     */
    private Date deleteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_public_account.delete_flag
     *
     * @mbggenerated
     */
    private Integer deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_public_account.sys_user_id
     *
     * @mbggenerated
     */
    private Long sysUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_public_account.desc
     *
     * @mbggenerated
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_public_account.jssdk_security_domain
     *
     * @mbggenerated
     */
    private String jssdkSecurityDomain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_public_account.oAuth2_login_callback_domain
     *
     * @mbggenerated
     */
    private String oauth2LoginCallbackDomain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_public_account.settlement_status
     *
     * @mbggenerated
     */
    private Integer settlementStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wechat_public_account
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_public_account.id
     *
     * @return the value of wechat_public_account.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_public_account.id
     *
     * @param id the value for wechat_public_account.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_public_account.account_id
     *
     * @return the value of wechat_public_account.account_id
     *
     * @mbggenerated
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_public_account.account_id
     *
     * @param accountId the value for wechat_public_account.account_id
     *
     * @mbggenerated
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_public_account.account_name
     *
     * @return the value of wechat_public_account.account_name
     *
     * @mbggenerated
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_public_account.account_name
     *
     * @param accountName the value for wechat_public_account.account_name
     *
     * @mbggenerated
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_public_account.app_id
     *
     * @return the value of wechat_public_account.app_id
     *
     * @mbggenerated
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_public_account.app_id
     *
     * @param appId the value for wechat_public_account.app_id
     *
     * @mbggenerated
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_public_account.app_secret
     *
     * @return the value of wechat_public_account.app_secret
     *
     * @mbggenerated
     */
    public String getAppSecret() {
        return appSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_public_account.app_secret
     *
     * @param appSecret the value for wechat_public_account.app_secret
     *
     * @mbggenerated
     */
    public void setAppSecret(String appSecret) {
        this.appSecret = appSecret == null ? null : appSecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_public_account.token
     *
     * @return the value of wechat_public_account.token
     *
     * @mbggenerated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_public_account.token
     *
     * @param token the value for wechat_public_account.token
     *
     * @mbggenerated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_public_account.ticket
     *
     * @return the value of wechat_public_account.ticket
     *
     * @mbggenerated
     */
    public String getTicket() {
        return ticket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_public_account.ticket
     *
     * @param ticket the value for wechat_public_account.ticket
     *
     * @mbggenerated
     */
    public void setTicket(String ticket) {
        this.ticket = ticket == null ? null : ticket.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_public_account.valid_state
     *
     * @return the value of wechat_public_account.valid_state
     *
     * @mbggenerated
     */
    public Integer getValidState() {
        return validState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_public_account.valid_state
     *
     * @param validState the value for wechat_public_account.valid_state
     *
     * @mbggenerated
     */
    public void setValidState(Integer validState) {
        this.validState = validState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_public_account.url
     *
     * @return the value of wechat_public_account.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_public_account.url
     *
     * @param url the value for wechat_public_account.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_public_account.aes_key
     *
     * @return the value of wechat_public_account.aes_key
     *
     * @mbggenerated
     */
    public String getAesKey() {
        return aesKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_public_account.aes_key
     *
     * @param aesKey the value for wechat_public_account.aes_key
     *
     * @mbggenerated
     */
    public void setAesKey(String aesKey) {
        this.aesKey = aesKey == null ? null : aesKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_public_account.partener_id
     *
     * @return the value of wechat_public_account.partener_id
     *
     * @mbggenerated
     */
    public String getPartenerId() {
        return partenerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_public_account.partener_id
     *
     * @param partenerId the value for wechat_public_account.partener_id
     *
     * @mbggenerated
     */
    public void setPartenerId(String partenerId) {
        this.partenerId = partenerId == null ? null : partenerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_public_account.partener_key
     *
     * @return the value of wechat_public_account.partener_key
     *
     * @mbggenerated
     */
    public String getPartenerKey() {
        return partenerKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_public_account.partener_key
     *
     * @param partenerKey the value for wechat_public_account.partener_key
     *
     * @mbggenerated
     */
    public void setPartenerKey(String partenerKey) {
        this.partenerKey = partenerKey == null ? null : partenerKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_public_account.status
     *
     * @return the value of wechat_public_account.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_public_account.status
     *
     * @param status the value for wechat_public_account.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_public_account.create_time
     *
     * @return the value of wechat_public_account.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_public_account.create_time
     *
     * @param createTime the value for wechat_public_account.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_public_account.update_time
     *
     * @return the value of wechat_public_account.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_public_account.update_time
     *
     * @param updateTime the value for wechat_public_account.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_public_account.delete_time
     *
     * @return the value of wechat_public_account.delete_time
     *
     * @mbggenerated
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_public_account.delete_time
     *
     * @param deleteTime the value for wechat_public_account.delete_time
     *
     * @mbggenerated
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_public_account.delete_flag
     *
     * @return the value of wechat_public_account.delete_flag
     *
     * @mbggenerated
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_public_account.delete_flag
     *
     * @param deleteFlag the value for wechat_public_account.delete_flag
     *
     * @mbggenerated
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_public_account.sys_user_id
     *
     * @return the value of wechat_public_account.sys_user_id
     *
     * @mbggenerated
     */
    public Long getSysUserId() {
        return sysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_public_account.sys_user_id
     *
     * @param sysUserId the value for wechat_public_account.sys_user_id
     *
     * @mbggenerated
     */
    public void setSysUserId(Long sysUserId) {
        this.sysUserId = sysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_public_account.desc
     *
     * @return the value of wechat_public_account.desc
     *
     * @mbggenerated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_public_account.desc
     *
     * @param desc the value for wechat_public_account.desc
     *
     * @mbggenerated
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_public_account.jssdk_security_domain
     *
     * @return the value of wechat_public_account.jssdk_security_domain
     *
     * @mbggenerated
     */
    public String getJssdkSecurityDomain() {
        return jssdkSecurityDomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_public_account.jssdk_security_domain
     *
     * @param jssdkSecurityDomain the value for wechat_public_account.jssdk_security_domain
     *
     * @mbggenerated
     */
    public void setJssdkSecurityDomain(String jssdkSecurityDomain) {
        this.jssdkSecurityDomain = jssdkSecurityDomain == null ? null : jssdkSecurityDomain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_public_account.oAuth2_login_callback_domain
     *
     * @return the value of wechat_public_account.oAuth2_login_callback_domain
     *
     * @mbggenerated
     */
    public String getOauth2LoginCallbackDomain() {
        return oauth2LoginCallbackDomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_public_account.oAuth2_login_callback_domain
     *
     * @param oauth2LoginCallbackDomain the value for wechat_public_account.oAuth2_login_callback_domain
     *
     * @mbggenerated
     */
    public void setOauth2LoginCallbackDomain(String oauth2LoginCallbackDomain) {
        this.oauth2LoginCallbackDomain = oauth2LoginCallbackDomain == null ? null : oauth2LoginCallbackDomain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_public_account.settlement_status
     *
     * @return the value of wechat_public_account.settlement_status
     *
     * @mbggenerated
     */
    public Integer getSettlementStatus() {
        return settlementStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_public_account.settlement_status
     *
     * @param settlementStatus the value for wechat_public_account.settlement_status
     *
     * @mbggenerated
     */
    public void setSettlementStatus(Integer settlementStatus) {
        this.settlementStatus = settlementStatus;
    }
}