package cn.zhangxd.auth.dao;

import cn.zhangxd.auth.pojo.Authorities;
import cn.zhangxd.auth.pojo.AuthoritiesExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface AuthoritiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorities
     *
     * @mbggenerated
     */
    int countByExample(AuthoritiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorities
     *
     * @mbggenerated
     */
    int deleteByExample(AuthoritiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorities
     *
     * @mbggenerated
     */
    int insert(Authorities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorities
     *
     * @mbggenerated
     */
    int insertSelective(Authorities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorities
     *
     * @mbggenerated
     */
    List<Authorities> selectByExample(AuthoritiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorities
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Authorities record, @Param("example") AuthoritiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorities
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Authorities record, @Param("example") AuthoritiesExample example);
}