package com.entrobus.credit.manager.dao;

import com.entrobus.credit.pojo.manager.LoanInterestRate;
import com.entrobus.credit.pojo.manager.LoanInterestRateExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LoanInterestRateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_interest_rate
     *
     * @mbggenerated
     */
    int countByExample(LoanInterestRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_interest_rate
     *
     * @mbggenerated
     */
    int deleteByExample(LoanInterestRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_interest_rate
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_interest_rate
     *
     * @mbggenerated
     */
    int insert(LoanInterestRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_interest_rate
     *
     * @mbggenerated
     */
    int insertSelective(LoanInterestRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_interest_rate
     *
     * @mbggenerated
     */
    List<LoanInterestRate> selectByExample(LoanInterestRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_interest_rate
     *
     * @mbggenerated
     */
    LoanInterestRate selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_interest_rate
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LoanInterestRate record, @Param("example") LoanInterestRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_interest_rate
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LoanInterestRate record, @Param("example") LoanInterestRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_interest_rate
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LoanInterestRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table loan_interest_rate
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LoanInterestRate record);

    int insertBatchSelective(List<LoanInterestRate> records);

    int updateBatchByPrimaryKeySelective(List<LoanInterestRate> records);
}