server:
  port: 8092
  
msg: file-service

eureka:
  instance:
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}

spring:
  redis:
    cluster:
      nodes:
        - 10.1.1.241:8000
        - 10.1.1.241:8001
        - 10.1.1.241:8002
        - 10.1.1.241:8003
        - 10.1.1.241:8004
        - 10.1.1.241:8005

security:
  user:
    name: user
    password: password
#  oauth2:
#    client:
#      clientId: order-service
#      clientSecret: ${security.user.password}
#      accessTokenUri: http://${authserver.hostname}:${authserver.port}${authserver.contextPath}/oauth/token
#      grant-type: client_credentials
#      scope: server
