package com.entrobus.credit.pojo.log;

import java.io.Serializable;
import java.util.Date;

public class SysLoginLog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.sys_user_id
     *
     * @mbggenerated
     */
    private String sysUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.browser
     *
     * @mbggenerated
     */
    private String browser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.operation_system
     *
     * @mbggenerated
     */
    private String operationSystem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.login_time
     *
     * @mbggenerated
     */
    private Date loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_login_log.platform
     *
     * @mbggenerated
     */
    private Integer platform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_login_log
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.id
     *
     * @return the value of sys_login_log.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.id
     *
     * @param id the value for sys_login_log.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.sys_user_id
     *
     * @return the value of sys_login_log.sys_user_id
     *
     * @mbggenerated
     */
    public String getSysUserId() {
        return sysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.sys_user_id
     *
     * @param sysUserId the value for sys_login_log.sys_user_id
     *
     * @mbggenerated
     */
    public void setSysUserId(String sysUserId) {
        this.sysUserId = sysUserId == null ? null : sysUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.address
     *
     * @return the value of sys_login_log.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.address
     *
     * @param address the value for sys_login_log.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.browser
     *
     * @return the value of sys_login_log.browser
     *
     * @mbggenerated
     */
    public String getBrowser() {
        return browser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.browser
     *
     * @param browser the value for sys_login_log.browser
     *
     * @mbggenerated
     */
    public void setBrowser(String browser) {
        this.browser = browser == null ? null : browser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.operation_system
     *
     * @return the value of sys_login_log.operation_system
     *
     * @mbggenerated
     */
    public String getOperationSystem() {
        return operationSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.operation_system
     *
     * @param operationSystem the value for sys_login_log.operation_system
     *
     * @mbggenerated
     */
    public void setOperationSystem(String operationSystem) {
        this.operationSystem = operationSystem == null ? null : operationSystem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.login_time
     *
     * @return the value of sys_login_log.login_time
     *
     * @mbggenerated
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.login_time
     *
     * @param loginTime the value for sys_login_log.login_time
     *
     * @mbggenerated
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.create_time
     *
     * @return the value of sys_login_log.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.create_time
     *
     * @param createTime the value for sys_login_log.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_login_log.platform
     *
     * @return the value of sys_login_log.platform
     *
     * @mbggenerated
     */
    public Integer getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_login_log.platform
     *
     * @param platform the value for sys_login_log.platform
     *
     * @mbggenerated
     */
    public void setPlatform(Integer platform) {
        this.platform = platform;
    }
}