package com.entrobus.credit.wechat.dao;

import com.entrobus.credit.pojo.wechat.WechatPublicAccount;
import com.entrobus.credit.pojo.wechat.WechatPublicAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WechatPublicAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_public_account
     *
     * @mbggenerated
     */
    int countByExample(WechatPublicAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_public_account
     *
     * @mbggenerated
     */
    int deleteByExample(WechatPublicAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_public_account
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_public_account
     *
     * @mbggenerated
     */
    int insert(WechatPublicAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_public_account
     *
     * @mbggenerated
     */
    int insertSelective(WechatPublicAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_public_account
     *
     * @mbggenerated
     */
    List<WechatPublicAccount> selectByExample(WechatPublicAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_public_account
     *
     * @mbggenerated
     */
    WechatPublicAccount selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_public_account
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WechatPublicAccount record, @Param("example") WechatPublicAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_public_account
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WechatPublicAccount record, @Param("example") WechatPublicAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_public_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WechatPublicAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_public_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WechatPublicAccount record);

    int insertBatchSelective(List<WechatPublicAccount> records);

    int updateBatchByPrimaryKeySelective(List<WechatPublicAccount> records);
}