package com.entrobus.credit.wechat.dao;

import com.entrobus.credit.pojo.wechat.WechatReqMsgLog;
import com.entrobus.credit.pojo.wechat.WechatReqMsgLogExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface WechatReqMsgLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_req_msg_log
     *
     * @mbggenerated
     */
    int countByExample(WechatReqMsgLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_req_msg_log
     *
     * @mbggenerated
     */
    int deleteByExample(WechatReqMsgLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_req_msg_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_req_msg_log
     *
     * @mbggenerated
     */
    int insert(WechatReqMsgLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_req_msg_log
     *
     * @mbggenerated
     */
    int insertSelective(WechatReqMsgLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_req_msg_log
     *
     * @mbggenerated
     */
    List<WechatReqMsgLog> selectByExample(WechatReqMsgLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_req_msg_log
     *
     * @mbggenerated
     */
    WechatReqMsgLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_req_msg_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WechatReqMsgLog record, @Param("example") WechatReqMsgLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_req_msg_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WechatReqMsgLog record, @Param("example") WechatReqMsgLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_req_msg_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WechatReqMsgLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_req_msg_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WechatReqMsgLog record);

    int insertBatchSelective(List<WechatReqMsgLog> records);

    int updateBatchByPrimaryKeySelective(List<WechatReqMsgLog> records);
}